In [1]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 104, 106, None],
    "Name": ["Srikar", "Rahul", "Ananya", "Priya", "Priya", None, "Kiran"],
    "Age": [21, 22, None, 24, 24, 23, "Twenty"],
    "Join_Date": ["2024-01-15", "15/02/2024", "2024/03/10", "April 5 2024", "April 5 2024", None, "2024-13-01"],
    "Salary": [25000, 30000, 28000, None, None, 32000, 27000]
}

df = pd.DataFrame(data)

df

      ID    Name     Age     Join_Date   Salary
0  101.0  Srikar      21    2024-01-15  25000.0
1  102.0   Rahul      22    15/02/2024  30000.0
2  103.0  Ananya    None    2024/03/10  28000.0
3  104.0   Priya      24  April 5 2024      NaN
4  104.0   Priya      24  April 5 2024      NaN
5  106.0    None      23          None  32000.0
6    NaN   Kiran  Twenty    2024-13-01  27000.0

In [2]:
df.isnull().sum()

ID           1
Name         1
Age          1
Join_Date    1
Salary       2
dtype: int64

In [3]:
df = df.drop_duplicates()

df

      ID    Name     Age     Join_Date   Salary
0  101.0  Srikar      21    2024-01-15  25000.0
1  102.0   Rahul      22    15/02/2024  30000.0
2  103.0  Ananya    None    2024/03/10  28000.0
3  104.0   Priya      24  April 5 2024      NaN
5  106.0    None      23          None  32000.0
6    NaN   Kiran  Twenty    2024-13-01  27000.0

In [4]:
df["Age"] = df["Age"].replace("Twenty", 20)

df["Age"] = pd.to_numeric(df["Age"])

df["Age"].fillna(df["Age"].mean(), inplace=True)

df["Salary"].fillna(df["Salary"].mean(), inplace=True)

df["Name"].fillna("Unknown", inplace=True)

df

/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Age"] = df["Age"].replace("Twenty", 20)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].replace("Twenty", 20)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = pd.to_numeric(df["Age"])
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"].fillna(df["Age"].mean(), inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"].fillna(df["Salary"].mean(), inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/2500310363.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Name"].fillna("Unknown", inplace=True)

      ID     Name   Age     Join_Date   Salary
0  101.0   Srikar  21.0    2024-01-15  25000.0
1  102.0    Rahul  22.0    15/02/2024  30000.0
2  103.0   Ananya  22.0    2024/03/10  28000.0
3  104.0    Priya  24.0  April 5 2024  28400.0
5  106.0  Unknown  23.0          None  32000.0
6    NaN    Kiran  20.0    2024-13-01  27000.0

In [5]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

df

/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/4029590123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

      ID     Name   Age  Join_Date   Salary
0  101.0   Srikar  21.0 2024-01-15  25000.0
1  102.0    Rahul  22.0        NaT  30000.0
2  103.0   Ananya  22.0        NaT  28000.0
3  104.0    Priya  24.0        NaT  28400.0
5  106.0  Unknown  23.0        NaT  32000.0
6    NaN    Kiran  20.0        NaT  27000.0

In [6]:
df["Join_Date"].fillna("2024-01-01", inplace=True)

df

/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/1810272592.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Join_Date"].fillna("2024-01-01", inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/1810272592.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Join_Date"].fillna("2024-01-01", inplace=True)

      ID     Name   Age  Join_Date   Salary
0  101.0   Srikar  21.0 2024-01-15  25000.0
1  102.0    Rahul  22.0 2024-01-01  30000.0
2  103.0   Ananya  22.0 2024-01-01  28000.0
3  104.0    Priya  24.0 2024-01-01  28400.0
5  106.0  Unknown  23.0 2024-01-01  32000.0
6    NaN    Kiran  20.0 2024-01-01  27000.0

In [7]:
df["ID"].duplicated().sum()

np.int64(0)

In [8]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nDataset Info:")
print(df.info())

Missing Values:
ID           1
Name         0
Age          0
Join_Date    0
Salary       0
dtype: int64

Duplicate Rows:
0

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         5 non-null      float64
 1   Name       6 non-null      object
 2   Age        6 non-null      float64
 3   Join_Date  6 non-null      datetime64[ns]
 4   Salary     6 non-null      float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 288.0+ bytes
None

In [9]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [10]:
df["ID"].fillna(107, inplace=True)

df

/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/548886193.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["ID"].fillna(107, inplace=True)
/var/folders/ph/6jtdbccs7x515xm9dr_twjc00000gn/T/ipykernel_97545/548886193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ID"].fillna(107, inplace=True)

      ID     Name   Age  Join_Date   Salary
0  101.0   Srikar  21.0 2024-01-15  25000.0
1  102.0    Rahul  22.0 2024-01-01  30000.0
2  103.0   Ananya  22.0 2024-01-01  28000.0
3  104.0    Priya  24.0 2024-01-01  28400.0
5  106.0  Unknown  23.0 2024-01-01  32000.0
6  107.0    Kiran  20.0 2024-01-01  27000.0

In [11]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Final cleaned dataset saved successfully!")

Final cleaned dataset saved successfully!